# Generated by Django 5.2.16 on 2026-07-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Backtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_key", models.CharField(max_length=50)),
                ("strategy_label", models.CharField(max_length=120)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("initial_cash", models.FloatField(default=100000.0)),
                (
                    "commission",
                    models.FloatField(
                        default=0.001, help_text="Fraction charged per trade"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("final_value", models.FloatField(blank=True, null=True)),
                ("total_return", models.FloatField(blank=True, null=True)),
                ("buy_hold_return", models.FloatField(blank=True, null=True)),
                ("max_drawdown", models.FloatField(blank=True, null=True)),
                ("sharpe_ratio", models.FloatField(blank=True, null=True)),
                ("num_trades", models.IntegerField(default=0)),
                ("win_rate", models.FloatField(blank=True, null=True)),
                ("equity_curve", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to="trading.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("price", models.FloatField()),
                ("shares", models.FloatField()),
                ("value", models.FloatField()),
                ("pnl", models.FloatField(blank=True, null=True)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.backtest",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="trading.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "date"], name="trading_pri_stock_i_e26595_idx"
                    )
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
