# Generated by Django 5.2.16 on 2026-07-19 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horizon_days", models.IntegerField(default=5)),
                (
                    "threshold",
                    models.FloatField(
                        default=0.1, help_text="Upside target as a fraction"
                    ),
                ),
                ("n_sims", models.IntegerField(default=10000)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ensemble", "アンサンブル（ブートストラップ＋GBM）"),
                            ("bootstrap", "ヒストリカル・ブートストラップ"),
                            ("gbm", "パラメトリック GBM"),
                        ],
                        default="ensemble",
                        max_length=20,
                    ),
                ),
                ("reference_price", models.FloatField()),
                ("hit_probability", models.FloatField()),
                ("prob_up", models.FloatField(default=0.0)),
                ("expected_max_return", models.FloatField(default=0.0)),
                ("median_max_return", models.FloatField(default=0.0)),
                ("p5_return", models.FloatField(default=0.0)),
                ("p50_return", models.FloatField(default=0.0)),
                ("p95_return", models.FloatField(default=0.0)),
                ("news_text", models.TextField(blank=True)),
                ("news_sentiment", models.FloatField(default=0.0)),
                ("drift_adjust", models.FloatField(default=0.0)),
                ("vol_adjust", models.FloatField(default=1.0)),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("bands", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="trading.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
